import pytest
from datetime import datetime
from fastapi.testclient import TestClient
from app.main import app
from app.db import db
from app.models import StateThread, MemberProfile, LoanApplication
from app.agents import process_ussd_sms_loop, determine_repayment_date
from app.compliance import (
    scrub_sensitive_proxies, 
    dignity_message_interceptor, 
    verify_data_residency,
    clear_anomaly_alerts,
    get_anomaly_alerts,
    record_and_analyze_telemetry
)

client = TestClient(app)

@pytest.fixture(autouse=True)
def setup_teardown():
    # Clear active states in db before each test
    db.clear()
    clear_anomaly_alerts()
    yield

# --- TEST 1: RED TEAM SEASONAL VENDOR (Auma Nakami - Shea Butter Vendor) ---
def test_shea_butter_vendor_escalation():
    """
    Test that a 38-year-old shea butter vendor in Busia requesting KES 10,000
    under stress triggers automated handoff and is ESCALATED due to the vulnerability 
    matrix (2 children under age 5). It also verifies the specialist assignment (John).
    """
    # 1. Verify profile is loaded in mock db
    profile = db.get_profile("member_busia_shea")
    assert profile is not None
    assert profile.crop_type == "shea_butter"
    assert len(profile.estimated_child_ages) == 4
    
    # Check children under 5 (ages 3, 4)
    children_under_5 = sum(1 for age in profile.estimated_child_ages if age < 5)
    assert children_under_5 == 2
    
    # 2. Simulate inbound SMS indicating intense financial stress
    # Inbound message: "Drought killed my crops. Need KES 10000 for school fees."
    payload = {
        "member_id": "member_busia_shea",
        "text": "Drought killed my crops. Need KES 10000 for school fees.",
        "sub_county": "Busia Central"
    }
    
    response = client.post("/sms/inbound", json=payload)
    assert response.status_code == 200
    data = response.json()
    
    # 3. Check transition results
    state = db.get_state("member_busia_shea")
    
    # Scout should have handed off to Guardian, which should have escalated to Hunter
    assert state.current_agent == "hunter"
    assert state.human_escalation_status == "pending_review"
    assert "INTENSE_STRESS_DETECTED" in state.financial_stress_flags
    assert "MULTIPLE_UNDER_5_DEPENDENTS" in state.financial_stress_flags
    
    # 4. Check briefing packet generated by Hunter Agent
    briefing_packet = state.telemetry_metadata.get("briefing_packet")
    assert briefing_packet is not None
    assert "Human Loan Officer Briefing Packet" in briefing_packet
    assert "**Assigned Specialist:** John" in briefing_packet  # John is shea butter specialist
    assert "Busia Central" in briefing_packet
    assert "Shea_Butter" in briefing_packet
    
    # 5. Check response message content is empathetic and references officer John
    assert "John" in data["text"]
    assert "prioritized for human review" in data["text"]


def test_shea_butter_vendor_no_escalation_auto_approve():
    """
    If we modify the vendor's profile temporarily to have only 1 child under 5 (non-escalating household risk),
    and she requests a loan ≤ KES 15,000 aligned with crop peaks, it should auto-approve.
    """
    # Temporarily alter children ages to check triage logic
    profile = db.get_profile("member_busia_shea")
    profile.estimated_child_ages = [3, 6, 8, 12]  # Only 1 child under 5 (age 3)
    
    # Directly process the orchestrator state to test Guardian Triage
    state = StateThread(member_id="member_busia_shea", current_agent="guardian")
    
    # Repayment date check
    _, is_aligned = determine_repayment_date(datetime.now())
    
    # Run loop
    state, response_text = process_ussd_sms_loop(state, profile, "need loan of 12000")
    
    if is_aligned:
        assert state.loan_application.status == "approved"
        assert "approved" in response_text.lower()
    else:
        # If today is a non-peak alignment day
        assert state.loan_application.status == "denied"
        assert "unsuccessful" in response_text.lower() or "protective" in response_text.lower()


# --- TEST 2: SALARIED NAIROBI CLERK COMPARED TO SEASONAL VENDOR ---
def test_salaried_clerk_profile():
    """
    Test that the salaried clerk has a different risk profile (low income variance index),
    and is routed directly to the appropriate loan officer specialist (David) if escalated.
    """
    profile = db.get_profile("member_nairobi_clerk")
    assert profile is not None
    assert profile.is_salaried is True
    assert profile.monthly_salary == 35000.0
    
    # Send a request over KES 15,000 to force escalation to Hunter
    payload = {
        "member_id": "member_nairobi_clerk",
        "text": "Apply for KES 25000 loan to repair my home.",
        "sub_county": "Westlands"
    }
    
    response = client.post("/sms/inbound", json=payload)
    assert response.status_code == 200
    
    state = db.get_state("member_nairobi_clerk")
    assert state.current_agent == "hunter"
    assert state.human_escalation_status == "pending_review"
    
    briefing_packet = state.telemetry_metadata.get("briefing_packet")
    assert "David" in briefing_packet  # David handles salaried specialists
    assert "**Income Variance Index:** 0.1" in briefing_packet  # Salaried has low income variance


# --- TEST 3: BIAS MITIGATION FILTER (PROXY VARIABLES) ---
def test_bias_mitigation_filter():
    """
    Verify that sensitive fields and traditional crop proxies (e.g. shea_butter, matooke)
    are scrubbed or flagged in the raw features list, appending alerts.
    """
    raw_data = {
        "gender": "female",
        "tribe": "Luhya",
        "crop_type": "shea_butter",
        "sub_county": "Busia Central"
    }
    
    scrubbed = scrub_sensitive_proxies(raw_data)
    
    # Explicit variables should be removed
    assert "gender" not in scrubbed
    assert "tribe" not in scrubbed
    
    # Crop proxy should be scrubbed
    assert scrubbed["crop_type"] == "[REDACTED_GENDER_PROXY]"
    
    # Alerts should record variables scrubbed
    alerts = scrubbed.get("_bias_mitigation_alerts", [])
    assert "gender" in alerts
    assert "tribe" in alerts
    assert "crop_type (gender proxy)" in alerts


# --- TEST 4: DIGNITY LEXICON GUARDRAILS ---
def test_dignity_lexicon_guardrail():
    """
    Ensure clinical terms like 'high risk' or 'unreliable' are intercepted
    and replaced with polite, educational language.
    """
    harsh_message = "Your loan is denied because your income is unreliable and you are high risk."
    rewritten = dignity_message_interceptor(harsh_message)
    
    assert "unreliable" not in rewritten
    assert "high risk" not in rewritten
    assert "subject to seasonal fluctuations" in rewritten
    assert "temporary agricultural cash flow changes" in rewritten
    assert "Ujima SACCO works with you" in rewritten


# --- TEST 5: TELEMETRY ANOMALY DETECTION ---
def test_telemetry_anomaly_detection():
    """
    Verify that if the approval rate drops by more than 30% in a sub-county,
    a system-wide flag is triggered.
    """
    sub_county = "Busia Central"
    
    # Baseline for Busia Central is initialized as 8 approvals in 10 tests (80%).
    # We record 5 consecutive denials to drop recent rate to 0%.
    # Drop: (0.80 - 0.0) / 0.80 = 100% drop, which is > 30% threshold.
    
    for _ in range(5):
        record_and_analyze_telemetry(sub_county, approved=False)
        
    alerts = get_anomaly_alerts()
    assert len(alerts) > 0
    assert any("Busia Central" in alert for alert in alerts)
    assert any("dropped" in alert for alert in alerts)


# --- TEST 6: DATA SOVEREIGNTY CHECKS ---
def test_data_sovereignty_checks():
    """
    Ensure S3/DB configs targeting foreign regions throw connection exceptions.
    """
    # af-south-1 (local African zone) should pass
    local_uri = "s3://ujima-bucket.s3.af-south-1.amazonaws.com"
    assert verify_data_residency(local_uri) is True
    
    # us-east-1 (foreign region) should fail
    foreign_uri = "s3://ujima-bucket.s3.us-east-1.amazonaws.com"
    with pytest.raises(ConnectionError) as excinfo:
        verify_data_residency(foreign_uri)
    assert "DATA SOVEREIGNTY VIOLATION" in str(excinfo.value)


# --- TEST 7: USSD RUNTIME COMMANDS ---
def test_ussd_runtime_commands():
    """
    Verify that commands *#700# (pause) and *#733# (takeover) execute correctly.
    """
    profile = db.get_profile("member_busia_shea")
    state = StateThread(member_id="member_busia_shea")
    
    # 1. Trigger Pause Command
    state, resp = process_ussd_sms_loop(state, profile, "*#700#")
    assert state.paused is True
    assert "PAUSED" in resp
    
    # Any incoming message while paused should return a pause reminder
    state, resp = process_ussd_sms_loop(state, profile, "hello")
    assert "currently paused" in resp
    
    # Unpause
    state, resp = process_ussd_sms_loop(state, profile, "*#700#")
    assert state.paused is False
    assert "RESUMED" in resp
    
    # 2. Trigger Takeover Command *#733#
    state, resp = process_ussd_sms_loop(state, profile, "*#733#")
    assert state.current_agent == "hunter"
    assert state.human_escalation_status == "pending_review"
    assert "prioritized for human review" in resp
